workflows:
  sample-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.fownd.fownd
      vars:
        APP_ID: 6447272649
        APP_STORE_CONNECT_API_KEY: CodeMagic
      flutter: stable
      xcode: latest
      cocoapods: default

    # Build and test scripts
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Build IPA for distribution
        script: flutter build ipa --release

    # Integrations and publishing sections
    integrations:
      app_store_connect: $APP_STORE_CONNECT_API_KEY
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        cancel_previous_submissions: true
