workflows:
  sample-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: Fownd
      vars:
        APP_ID: 6447272649 # <-- Put your APP ID here
        APP_STORE_CONNECT_API_KEY: Codemagic # <-- Put the name of your API key here
      xcode: latest
      cocoapods: default

    # Add your build and test scripts here

    # Add the integrations and publishing sections
    integrations:
      app_store_connect: $APP_STORE_CONNECT_API_KEY
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
