workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.fownd.fownd
      vars:
        APP_ID: app.fownd.fownd
        PROVISIONING_PROFILE: App-Store-profiles
        CERTIFICATE: signing-certificate
      flutter: stable
      xcode: 14.2
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Set up provisioning profiles
        script: |
          PROVISIONING_PROFILE_SPECIFIER="App-Store-profiles"
          echo "PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_SPECIFIER" >> $FLUTTER_ROOT/codemagic.yaml
      - name: Build and sign IPA for distribution
        script: |
          xcode-project use-profiles
          flutter build ipa --release
          xcodebuild archive -workspace ios/Runner.xcworkspace -scheme Runner -archivePath build/ios/archive/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportPath build/ios/ipa -exportOptionsPlist ios/Runner/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - steven@srsdesignsllc.com
